# Generated by Django 4.2.11 on 2024-11-17 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add book'), ('can_change_book', 'Can change book'), ('can_delete_book', 'Can delete book')]},
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_number',
            field=models.CharField(default='0000000000000', max_length=13),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
